from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field


class Severity(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class EventType(str, Enum):
    NETWORK_ALERT = "NETWORK_ALERT"
    AUTHENTICATION = "AUTHENTICATION"
    PROCESS_ACTIVITY = "PROCESS_ACTIVITY"
    NETWORK_CONNECTION = "NETWORK_CONNECTION"
    PACKET_METADATA = "PACKET_METADATA"
    SERVER_LOG = "SERVER_LOG"
    ASSET = "ASSET"
    VULNERABILITY = "VULNERABILITY"
    THREAT_INTEL = "THREAT_INTEL"


class SOCEvent(BaseModel):
    """
    Common event structure used by the SOC normalization layer.

    All telemetry sources should eventually be converted into this
    structure before being sent to the backend.
    """

    model_config = ConfigDict(extra="allow")

    event_id: str = Field(min_length=1)
    timestamp: datetime

    source: str = Field(min_length=1)
    event_type: EventType

    severity: Severity = Severity.MEDIUM

    source_ip: str | None = None
    destination_ip: str | None = None

    source_port: int | None = Field(default=None, ge=1, le=65535)
    destination_port: int | None = Field(default=None, ge=1, le=65535)

    protocol: str | None = None

    attack_type: str | None = None
    mitre_technique: str | None = None

    asset_id: str | None = None
    hostname: str | None = None

    username: str | None = None

    result: str | None = None

    message: str | None = None

    metadata: dict[str, Any] = Field(default_factory=dict)


class SOCAlert(SOCEvent):
    """
    Normalized security alert generated by Suricata, Wazuh,
    or another SOC detection source.
    """

    event_type: EventType = EventType.NETWORK_ALERT

    attack_type: str = Field(min_length=1)


class AuthenticationEvent(SOCEvent):
    """
    Authentication evidence such as successful or failed SSH login.
    """

    event_type: EventType = EventType.AUTHENTICATION

    username: str = Field(min_length=1)
    result: str = Field(min_length=1)


class ProcessEvent(SOCEvent):
    """
    Host process activity used as investigation evidence.
    """

    event_type: EventType = EventType.PROCESS_ACTIVITY

    process: str = Field(min_length=1)
    parent_process: str | None = None


class NetworkConnectionEvent(SOCEvent):
    """
    Network connection evidence observed after or around an alert.
    """

    event_type: EventType = EventType.NETWORK_CONNECTION

    destination_ip: str = Field(min_length=1)
    destination_port: int = Field(ge=1, le=65535)


def validate_event(data: dict[str, Any]) -> SOCEvent:
    """
    Validate and convert an arbitrary normalized event into SOCEvent.
    """

    return SOCEvent.model_validate(data)


def event_to_dict(event: SOCEvent) -> dict[str, Any]:
    """
    Convert a validated SOC event into JSON-compatible data.
    """

    return event.model_dump(mode="json")


if __name__ == "__main__":
    example = SOCAlert(
        event_id="EVT-001",
        timestamp=datetime.now(),
        source="suricata",
        severity=Severity.HIGH,
        source_ip="192.168.56.20",
        destination_ip="192.168.56.10",
        destination_port=22,
        protocol="TCP",
        attack_type="SSH_BRUTE_FORCE",
        mitre_technique="T1110",
        message="Multiple SSH authentication attempts detected",
    )

    print(example.model_dump_json(indent=2))
